// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udvatdgwyqrfkhsusgyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdmF0ZGd3eXFyZmtoc3VzZ3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzA0MTgsImV4cCI6MjA3NDIwNjQxOH0.vKKuWT_yI0xAN2yVnMQ5tAeWpGW6dFxwvr0UFmvm4iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});